using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace Luke.Mvux.Generators;

[Generator]
public sealed class ViewModelGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidate(node),
                transform: static (ctx, ct) => GetTarget(ctx, ct))
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(candidates, static (spc, symbol) =>
        {
            var source = GenerateViewModel(symbol!);
            if (source != null)
                spc.AddSource($"{symbol!.Name}ViewModel.g.cs", source);
        });
    }

    private static bool IsCandidate(SyntaxNode node)
        => node is RecordDeclarationSyntax r &&
           r.Modifiers.Any(SyntaxKind.PartialKeyword) &&
           r.Modifiers.Any(SyntaxKind.PublicKeyword);

    private static INamedTypeSymbol? GetTarget(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var record = (RecordDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(record, ct) is not INamedTypeSymbol symbol)
            return null;
        if (!symbol.IsRecord || !symbol.Name.EndsWith("Model"))
            return null;
        return symbol;
    }

    private static string? GenerateViewModel(INamedTypeSymbol symbol)
    {
        var vmName = symbol.Name.Substring(0, symbol.Name.Length - 5) + "ViewModel";
        var ns = symbol.ContainingNamespace?.IsGlobalNamespace == false
            ? symbol.ContainingNamespace.ToDisplayString()
            : null;

        var props = new List<(string Name, PropKind Kind, string TypeArg)>();
        var cmds = new List<CommandSpec>();
        var passMethods = new List<IMethodSymbol>();
        var implicitCommandsEnabled = ResolveImplicitCommands(symbol);
        var implicitFeedParameterEnabled = ResolveImplicitFeedParameters(symbol);
        var feedSources = new Dictionary<string, FeedSource>(StringComparer.OrdinalIgnoreCase);

        foreach (var member in symbol.GetMembers())
        {
            if (member is IPropertySymbol p && p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            {
                if (IsInterface(p.Type, "IListState", "Luke.Mvux"))
                    props.Add((p.Name, PropKind.ListState, TypeArg(p.Type)));
                else if (IsInterface(p.Type, "IListFeed", "Luke.Mvux"))
                    props.Add((p.Name, PropKind.ListFeed, TypeArg(p.Type)));
                else if (IsInterface(p.Type, "IState", "Luke.Mvux"))
                {
                    props.Add((p.Name, PropKind.State, TypeArg(p.Type)));
                    feedSources[p.Name] = new FeedSource(p.Name, TypeArg(p.Type));
                }
                else if (IsInterface(p.Type, "IFeed", "Luke.Mvux"))
                {
                    props.Add((p.Name, PropKind.Feed, TypeArg(p.Type)));
                    feedSources[p.Name] = new FeedSource(p.Name, TypeArg(p.Type));
                }
            }
            else if (member is IMethodSymbol m && m.DeclaredAccessibility == Accessibility.Public
                     && !m.IsStatic && !m.IsImplicitlyDeclared && m.MethodKind == MethodKind.Ordinary)
            {
                var returnKind = GetReturnKind(m);
                if (returnKind == ReturnKind.Unsupported)
                    continue;

                if (!ResolveCommandEnabled(m, implicitCommandsEnabled))
                {
                    passMethods.Add(m);
                    continue;
                }

                if (TryBuildCommandSpec(m, returnKind, feedSources, implicitFeedParameterEnabled, out var spec))
                    cmds.Add(spec);
            }
        }

        if (props.Count == 0 && cmds.Count == 0 && passMethods.Count == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Windows.Input;");
        sb.AppendLine("using Luke.Mvux;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        var primaryCtor = symbol.InstanceConstructors
            .FirstOrDefault(c => !c.IsImplicitlyDeclared
                && !(c.Parameters.Length == 1 && SymbolEqualityComparer.Default.Equals(c.Parameters[0].Type, symbol)));

        var ctorParams = primaryCtor != null && primaryCtor.Parameters.Length > 0
            ? string.Join(", ", primaryCtor.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"))
            : "";
        var ctorArgs = primaryCtor != null && primaryCtor.Parameters.Length > 0
            ? string.Join(", ", primaryCtor.Parameters.Select(p => p.Name))
            : "";

        var hasState = props.Any(p => p.Kind == PropKind.State);

        sb.AppendLine($"public partial class {vmName} : INotifyPropertyChanged, IDisposable");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {symbol.Name} _model;");
        sb.AppendLine($"    public {symbol.Name} Model => _model;");
        sb.AppendLine("    private readonly CancellationTokenSource _cts = new CancellationTokenSource();");
        if (hasState)
            sb.AppendLine("    private readonly SynchronizationContext _syncContext = SynchronizationContext.Current ?? new SynchronizationContext();");
        sb.AppendLine();

        sb.AppendLine($"    public {vmName}({ctorParams})");
        sb.AppendLine("    {");
        sb.AppendLine($"        _model = new {symbol.Name}({ctorArgs});");
        foreach (var (name, kind, typeArg) in props)
        {
            var fieldName = "_" + char.ToLowerInvariant(name[0]) + name.Substring(1);
            if (kind == PropKind.State)
                sb.AppendLine($"        _ = Subscribe{name}Async(_cts.Token);");
            else if (kind == PropKind.ListFeed || kind == PropKind.ListState)
                sb.AppendLine($"        {fieldName} = new global::Luke.Mvux.ObservableListFeedView<{typeArg}>(_model.{name}, _cts.Token);");
        }
        foreach (var cmd in cmds)
        {
            var invoke = BuildCommandInvoke(cmd);
            var canExecute = cmd.ViewParameterType is null ? "null" : $"p => p is {cmd.ViewParameterType}";
            sb.AppendLine($"        {cmd.Name} = new AsyncCommand({invoke}, {canExecute});");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var method in passMethods)
        {
            var returnType = method.ReturnType.ToDisplayString();
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));
            var args = string.Join(", ", method.Parameters.Select(p => p.Name));

            sb.AppendLine($"    public {returnType} {method.Name}({parameters}) => _model.{method.Name}({args});");
            sb.AppendLine();
        }

        foreach (var (name, kind, typeArg) in props)
        {
            var fieldName = "_" + char.ToLowerInvariant(name[0]) + name.Substring(1);

            switch (kind)
            {
                case PropKind.State:
                    sb.AppendLine($"    private {typeArg}? {fieldName};");
                    sb.AppendLine($"    public {typeArg}? {name}");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        get => {fieldName};");
                    sb.AppendLine("        set");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            if (Equals({fieldName}, value)) return;");
                    sb.AppendLine($"            {fieldName} = value;");
                    sb.AppendLine("            OnPropertyChanged();");
                    sb.AppendLine($"            if (value != null) _ = _model.{name}.SetAsync(value, _cts.Token);");
                    sb.AppendLine($"            else _ = _model.{name}.SetNoneAsync(_cts.Token);");
                    sb.AppendLine("        }");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                    sb.AppendLine($"    private async Task Subscribe{name}Async(CancellationToken ct)");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        await foreach (var msg in _model.{name}.GetSource(ct))");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            var v = msg.Data.IsSome(out var val) ? val : default;");
                    sb.AppendLine($"            var captured = v;");
                    sb.AppendLine("#pragma warning disable CS4014");
                    sb.AppendLine($"            _syncContext.Post(_ =>");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                if (Equals({fieldName}, captured)) return;");
                    sb.AppendLine($"                {fieldName} = captured;");
                    sb.AppendLine("                OnPropertyChanged(nameof(" + name + "));");
                    sb.AppendLine("            }, null);");
                    sb.AppendLine("#pragma warning restore CS4014");
                    sb.AppendLine("        }");
                    sb.AppendLine("    }");
                    break;

                case PropKind.Feed:
                    sb.AppendLine($"    public global::Luke.Mvux.IFeed<{typeArg}> {name} => _model.{name};");
                    break;

                case PropKind.ListFeed:
                case PropKind.ListState:
                    sb.AppendLine($"    private readonly global::Luke.Mvux.ObservableListFeedView<{typeArg}> {fieldName};");
                    sb.AppendLine($"    public global::System.Collections.ObjectModel.ObservableCollection<{typeArg}> {name} => {fieldName};");
                    break;
            }
            sb.AppendLine();
        }

        foreach (var cmd in cmds)
        {
            var name = cmd.Name;
            sb.AppendLine($"    public global::Luke.Mvux.IAsyncCommand {name} {{ get; }}");
        }
        if (cmds.Count > 0) sb.AppendLine();

        sb.AppendLine("    public event PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine("    private void OnPropertyChanged([CallerMemberName] string? name = null)");
        sb.AppendLine("        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));");
        sb.AppendLine();

        sb.AppendLine("    public void Dispose() => _cts.Cancel();");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool IsInterface(ITypeSymbol type, string name, string ns)
    {
        if (type is not INamedTypeSymbol { IsGenericType: true } named) return false;
        var def = named.ConstructedFrom;
        return def.Name == name && def.ContainingNamespace?.ToDisplayString() == ns;
    }

    private static string TypeArg(ITypeSymbol type)
        => type is INamedTypeSymbol { TypeArguments.Length: > 0 } named
            ? named.TypeArguments[0].ToDisplayString()
            : "object";

    private enum PropKind { State, Feed, ListState, ListFeed }

    private enum ReturnKind { Unsupported, Void, Task, ValueTask }

    private static ReturnKind GetReturnKind(IMethodSymbol method)
    {
        if (method.ReturnsVoid)
            return ReturnKind.Void;

        if (method.ReturnType is not INamedTypeSymbol named)
            return ReturnKind.Unsupported;

        if (named.Name == "Task" && named.TypeArguments.Length == 0)
            return ReturnKind.Task;

        if (named.Name == "ValueTask" && named.TypeArguments.Length == 0)
            return ReturnKind.ValueTask;

        return ReturnKind.Unsupported;
    }

    private static bool TryBuildCommandSpec(
        IMethodSymbol method,
        ReturnKind returnKind,
        IReadOnlyDictionary<string, FeedSource> feedSources,
        bool implicitFeedParameterEnabled,
        out CommandSpec spec)
    {
        var hasCt = method.Parameters.Length > 0 && IsCancellationToken(method.Parameters[method.Parameters.Length - 1].Type);
        var scanCount = hasCt ? method.Parameters.Length - 1 : method.Parameters.Length;

        var args = new List<CommandArg>();
        string? viewParamType = null;
        string? viewParamName = null;

        for (var i = 0; i < scanCount; i++)
        {
            var p = method.Parameters[i];
            var feedProp = ResolveFeedProperty(p, feedSources, implicitFeedParameterEnabled);
            if (feedProp is not null)
            {
                args.Add(new CommandArg(p.Name, feedProp, p.Type.ToDisplayString(), true));
                continue;
            }

            if (viewParamType is not null)
            {
                spec = default;
                return false;
            }

            viewParamType = p.Type.ToDisplayString();
            viewParamName = p.Name;
            args.Add(new CommandArg(p.Name, null, viewParamType, false));
        }

        if (hasCt)
            args.Add(new CommandArg(method.Parameters[method.Parameters.Length - 1].Name, null, "System.Threading.CancellationToken", false));

        spec = new CommandSpec(method.Name, returnKind, viewParamType, viewParamName, hasCt, args);
        return true;
    }

    private static bool IsCancellationToken(ITypeSymbol type)
        => type.ToDisplayString() == "System.Threading.CancellationToken";

    private static bool ResolveImplicitCommands(INamedTypeSymbol modelSymbol)
    {
        var typeAttribute = modelSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Luke.Mvux.ImplicitCommandsAttribute");
        if (typeAttribute is not null)
            return GetBooleanAttributeValue(typeAttribute, defaultValue: true);

        var assemblyAttribute = modelSymbol.ContainingAssembly.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Luke.Mvux.ImplicitCommandsAttribute");
        if (assemblyAttribute is not null)
            return GetBooleanAttributeValue(assemblyAttribute, defaultValue: true);

        return true;
    }

    private static bool ResolveCommandEnabled(IMethodSymbol method, bool implicitCommandsEnabled)
    {
        var methodAttribute = method.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Luke.Mvux.CommandAttribute");
        if (methodAttribute is not null)
            return GetBooleanAttributeValue(methodAttribute, defaultValue: true);

        return implicitCommandsEnabled;
    }

    private static bool ResolveImplicitFeedParameters(INamedTypeSymbol modelSymbol)
    {
        var typeAttribute = modelSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Luke.Mvux.ImplicitFeedCommandParameterAttribute");
        if (typeAttribute is not null)
            return GetBooleanAttributeValue(typeAttribute, defaultValue: true);

        var assemblyAttribute = modelSymbol.ContainingAssembly.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Luke.Mvux.ImplicitFeedCommandParameterAttribute");
        if (assemblyAttribute is not null)
            return GetBooleanAttributeValue(assemblyAttribute, defaultValue: true);

        return true;
    }

    private static string? ResolveFeedProperty(
        IParameterSymbol parameter,
        IReadOnlyDictionary<string, FeedSource> feedSources,
        bool implicitFeedParameterEnabled)
    {
        var explicitFeedAttr = parameter.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Luke.Mvux.FeedParameterAttribute");

        if (explicitFeedAttr is not null)
        {
            if (explicitFeedAttr.ConstructorArguments.Length == 1
                && explicitFeedAttr.ConstructorArguments[0].Value is string explicitName
                && feedSources.TryGetValue(explicitName, out var explicitFeed)
                && explicitFeed.ValueType == parameter.Type.ToDisplayString())
                return explicitFeed.PropertyName;

            return null;
        }

        if (!implicitFeedParameterEnabled)
            return null;

        if (feedSources.TryGetValue(parameter.Name, out var implicitFeed)
            && implicitFeed.ValueType == parameter.Type.ToDisplayString())
            return implicitFeed.PropertyName;

        return null;
    }

    private static string BuildCommandInvoke(CommandSpec cmd)
    {
        var lines = new List<string>();
        foreach (var arg in cmd.Args)
        {
            if (!arg.IsFeed)
                continue;

            lines.Add($"var __{arg.Name} = await global::Luke.Mvux.FeedExtensions.GetCurrentAsync(_model.{arg.FeedPropertyName}, ct);");
        }

        var callArgs = string.Join(", ", cmd.Args.Select(a =>
            a.IsFeed
                ? $"__{a.Name}"
                : a.TypeName == "System.Threading.CancellationToken"
                    ? "ct"
                    : (cmd.ViewParameterName is not null && a.Name == cmd.ViewParameterName ? "arg" : a.Name)));

        var call = cmd.ReturnKind switch
        {
            ReturnKind.ValueTask => $"await _model.{cmd.Name}({callArgs});",
            ReturnKind.Task => $"await _model.{cmd.Name}({callArgs});",
            _ => $"_model.{cmd.Name}({callArgs});"
        };

        if (cmd.ViewParameterType is not null)
        {
            lines.Insert(0, $"if (p is not {cmd.ViewParameterType} arg) return;");
        }

        lines.Add(call);
        if (cmd.ReturnKind == ReturnKind.Void)
            lines.Add("return ValueTask.CompletedTask;");

        var body = string.Join(" ", lines);
        return cmd.ReturnKind switch
        {
            ReturnKind.ValueTask => $"async (p, ct) => {{ {body} }}",
            ReturnKind.Task => $"async (p, ct) => {{ {body} }}",
            _ => $"(p, ct) => {{ {body} }}"
        };
    }

    private static bool GetBooleanAttributeValue(AttributeData attribute, bool defaultValue)
    {
        if (attribute.ConstructorArguments.Length == 0)
            return defaultValue;

        var value = attribute.ConstructorArguments[0].Value;
        return value is bool b ? b : defaultValue;
    }

    private readonly record struct FeedSource(string PropertyName, string ValueType);

    private readonly record struct CommandArg(string Name, string? FeedPropertyName, string TypeName, bool IsFeed);

    private readonly record struct CommandSpec(
        string Name,
        ReturnKind ReturnKind,
        string? ViewParameterType,
        string? ViewParameterName,
        bool HasCt,
        IReadOnlyList<CommandArg> Args);
}
