using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace Luke.Mvux.Generators;

[Generator]
public sealed class ViewModelGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidate(node),
                transform: static (ctx, ct) => GetTarget(ctx, ct))
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(candidates, static (spc, symbol) =>
        {
            var source = GenerateViewModel(symbol!);
            if (source != null)
                spc.AddSource($"{symbol!.Name}ViewModel.g.cs", source);
        });
    }

    private static bool IsCandidate(SyntaxNode node)
        => node is RecordDeclarationSyntax r &&
           r.Modifiers.Any(SyntaxKind.PartialKeyword) &&
           r.Modifiers.Any(SyntaxKind.PublicKeyword);

    private static INamedTypeSymbol? GetTarget(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var record = (RecordDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(record, ct) is not INamedTypeSymbol symbol)
            return null;
        if (!symbol.IsRecord || !symbol.Name.EndsWith("Model"))
            return null;
        return symbol;
    }

    private static string? GenerateViewModel(INamedTypeSymbol symbol)
    {
        var vmName = symbol.Name.Substring(0, symbol.Name.Length - 5) + "ViewModel";
        var ns = symbol.ContainingNamespace?.IsGlobalNamespace == false
            ? symbol.ContainingNamespace.ToDisplayString()
            : null;

        var props = new List<(string Name, PropKind Kind, string TypeArg)>();
        var cmds = new List<(string Name, bool HasCt, bool IsValueTask)>();

        foreach (var member in symbol.GetMembers())
        {
            if (member is IPropertySymbol p && p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            {
                if (IsInterface(p.Type, "IListState", "Luke.Mvux"))
                    props.Add((p.Name, PropKind.ListState, TypeArg(p.Type)));
                else if (IsInterface(p.Type, "IListFeed", "Luke.Mvux"))
                    props.Add((p.Name, PropKind.ListFeed, TypeArg(p.Type)));
                else if (IsInterface(p.Type, "IState", "Luke.Mvux"))
                    props.Add((p.Name, PropKind.State, TypeArg(p.Type)));
                else if (IsInterface(p.Type, "IFeed", "Luke.Mvux"))
                    props.Add((p.Name, PropKind.Feed, TypeArg(p.Type)));
            }
            else if (member is IMethodSymbol m && m.DeclaredAccessibility == Accessibility.Public
                     && !m.IsStatic && m.MethodKind == MethodKind.Ordinary
                     && (m.ReturnType.Name == "ValueTask" || m.ReturnType.Name == "Task")
                     && ((INamedTypeSymbol)m.ReturnType).TypeArguments.Length == 0)
            {
                var hasCt = m.Parameters.Length == 1
                    && m.Parameters[0].Type.ToDisplayString() == "System.Threading.CancellationToken";
                var noParams = m.Parameters.Length == 0;
                if (hasCt || noParams)
                    cmds.Add((m.Name, hasCt, m.ReturnType.Name == "ValueTask"));
            }
        }

        if (props.Count == 0 && cmds.Count == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Windows.Input;");
        sb.AppendLine("using Luke.Mvux;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        var primaryCtor = symbol.InstanceConstructors
            .FirstOrDefault(c => !c.IsImplicitlyDeclared
                && !(c.Parameters.Length == 1 && SymbolEqualityComparer.Default.Equals(c.Parameters[0].Type, symbol)));

        var ctorParams = primaryCtor != null && primaryCtor.Parameters.Length > 0
            ? string.Join(", ", primaryCtor.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"))
            : "";
        var ctorArgs = primaryCtor != null && primaryCtor.Parameters.Length > 0
            ? string.Join(", ", primaryCtor.Parameters.Select(p => p.Name))
            : "";

        var hasState = props.Any(p => p.Kind == PropKind.State);

        sb.AppendLine($"public partial class {vmName} : INotifyPropertyChanged, IDisposable");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {symbol.Name} _model;");
        sb.AppendLine("    private readonly CancellationTokenSource _cts = new CancellationTokenSource();");
        if (hasState)
            sb.AppendLine("    private readonly SynchronizationContext _syncContext = SynchronizationContext.Current ?? new SynchronizationContext();");
        sb.AppendLine();

        sb.AppendLine($"    public {vmName}({ctorParams})");
        sb.AppendLine("    {");
        sb.AppendLine($"        _model = new {symbol.Name}({ctorArgs});");
        foreach (var (name, kind, typeArg) in props)
        {
            var fieldName = "_" + char.ToLowerInvariant(name[0]) + name.Substring(1);
            if (kind == PropKind.State)
                sb.AppendLine($"        _ = Subscribe{name}Async(_cts.Token);");
            else if (kind == PropKind.ListFeed || kind == PropKind.ListState)
                sb.AppendLine($"        {fieldName} = new global::Luke.Mvux.ObservableListFeedView<{typeArg}>(_model.{name}, _cts.Token);");
        }
        foreach (var (name, hasCt, isValueTask) in cmds)
        {
            string invoke;
            if (hasCt)
                invoke = isValueTask
                    ? $"() => _model.{name}(_cts.Token).AsTask()"
                    : $"() => _model.{name}(_cts.Token)";
            else
                invoke = isValueTask
                    ? $"() => _model.{name}().AsTask()"
                    : $"() => _model.{name}()";
            sb.AppendLine($"        {name} = new AsyncCommand({invoke});");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var (name, kind, typeArg) in props)
        {
            var fieldName = "_" + char.ToLowerInvariant(name[0]) + name.Substring(1);

            switch (kind)
            {
                case PropKind.State:
                    sb.AppendLine($"    private {typeArg}? {fieldName};");
                    sb.AppendLine($"    public {typeArg}? {name}");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        get => {fieldName};");
                    sb.AppendLine("        set");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            if (Equals({fieldName}, value)) return;");
                    sb.AppendLine($"            {fieldName} = value;");
                    sb.AppendLine("            OnPropertyChanged();");
                    sb.AppendLine($"            if (value != null) _ = _model.{name}.SetAsync(value, _cts.Token);");
                    sb.AppendLine($"            else _ = _model.{name}.SetNoneAsync(_cts.Token);");
                    sb.AppendLine("        }");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                    sb.AppendLine($"    private async Task Subscribe{name}Async(CancellationToken ct)");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        await foreach (var msg in _model.{name}.GetSource(ct))");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            var v = msg.Data.IsSome(out var val) ? val : default;");
                    sb.AppendLine($"            var captured = v;");
                    sb.AppendLine("#pragma warning disable CS4014");
                    sb.AppendLine($"            _syncContext.Post(_ =>");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                if (Equals({fieldName}, captured)) return;");
                    sb.AppendLine($"                {fieldName} = captured;");
                    sb.AppendLine("                OnPropertyChanged(nameof(" + name + "));");
                    sb.AppendLine("            }, null);");
                    sb.AppendLine("#pragma warning restore CS4014");
                    sb.AppendLine("        }");
                    sb.AppendLine("    }");
                    break;

                case PropKind.Feed:
                    sb.AppendLine($"    public global::Luke.Mvux.IFeed<{typeArg}> {name} => _model.{name};");
                    break;

                case PropKind.ListFeed:
                case PropKind.ListState:
                    sb.AppendLine($"    private readonly global::Luke.Mvux.ObservableListFeedView<{typeArg}> {fieldName};");
                    sb.AppendLine($"    public global::System.Collections.ObjectModel.ObservableCollection<{typeArg}> {name} => {fieldName};");
                    break;
            }
            sb.AppendLine();
        }

        foreach (var (name, _, __) in cmds)
            sb.AppendLine($"    public ICommand {name} {{ get; }}");
        if (cmds.Count > 0) sb.AppendLine();

        sb.AppendLine("    public event PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine("    private void OnPropertyChanged([CallerMemberName] string? name = null)");
        sb.AppendLine("        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));");
        sb.AppendLine();

        sb.AppendLine("    public void Dispose() => _cts.Cancel();");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool IsInterface(ITypeSymbol type, string name, string ns)
    {
        if (type is not INamedTypeSymbol { IsGenericType: true } named) return false;
        var def = named.ConstructedFrom;
        return def.Name == name && def.ContainingNamespace?.ToDisplayString() == ns;
    }

    private static string TypeArg(ITypeSymbol type)
        => type is INamedTypeSymbol { TypeArguments.Length: > 0 } named
            ? named.TypeArguments[0].ToDisplayString()
            : "object";

    private enum PropKind { State, Feed, ListState, ListFeed }
}
